// DO NOT EDIT THIS FILE. IT IS GENERATED BY THE BUCKET CLI AND WILL BE OVERWRITTEN.

export const generatedFeatures: string[];
export interface GeneratedFeatureTypes {
  feature1: {
    key: "feature1", 
    access: true, 
    config: undefined
  }, 
  feature2: {
    key: "feature2", 
    access: false, 
    config: string
  }, 
  feature3: {
    key: "feature3", 
    access: true, 
    config: {
      aiModel: string, 
      prompt: {
        text: string, 
        cheekyFactor: number
      }
    }
  }
}