export function getCursorRules() {
  return `
---
description: Guidelines for implementing feature flagging using Bucket feature management service
globs: "**/*.ts, **/*.tsx, **/*.js, **/*.jsx"
---

${rules}
`.trim();
}

export function getCopilotInstructions() {
  return rules;
}

const rules = /* markdown */ `
# Bucket Feature Management Service for LLMs

Bucket is a comprehensive feature management service offering feature flags, user feedback collection, adoption tracking, and remote configuration for your applications across various JavaScript frameworks, particularly React, Next.js, Node.js, vanilla browser, CLI, and OpenFeature environments. Follow these best practices for feature flagging.

## Follow Official Documentation

- Refer to [Bucket's official documentation](mdc:https:/docs.bucket.co) for implementation details.
- Adhere to Bucket's recommended patterns for each framework.

## Bucket SDK Usage

- Configure \`BucketProvider\` or \`ReflagClient\` properly at application entry points.
- Leverage Bucket CLI for generating type-safe feature definitions.
- Write clean, type-safe code when applying Bucket feature flags.
- Follow established patterns in the project.

## Feature Flag Implementation

- Create reusable hooks and utilities for consistent feature management.
- Write clear comments for usage and checks of a feature flag.
- Properly handle feature loading states to prevent UI flashing.
- Implement proper error fallbacks when feature flag services are unavailable.

## Feature Targeting

- Use release stages to manage feature rollout (for example, development, staging, production).
- Use targeting modes effectively:
  - \`none\`: Feature is disabled for all targets.
  - \`some\`: Feature is enabled only for specified targets.
  - \`everyone\`: Feature is enabled for all targets.
- Target features to specific users, companies, or segments.

## Analytics and Feedback

- Track feature usage with Bucket analytics.
- Collect user feedback on features.
- Monitor feature adoption and health.

## Common Concepts

### Targeting Rules

Targeting rules are entities used in Bucket to describe the target audience of a given feature. The target audience refers to the users who can interact with the feature within your application. Additionally, each targeting rule contains a value that is used for the target audience.

### Feature Stages

Release stages in Bucket allow setting up app-wide feature access targeting rules. Each release stage defines targeting rules for each available environment. Later, during the development of new features, you can apply all those rules automatically by selecting an available release stage.

Release stages are useful tools when a standard release workflow is used in your organization.

Predefined stages:

- In development
- Internal
- Beta
- General Availability

### Segments

A segment entity in Bucket is a dynamic collection of companies. Segments' dynamic nature results from the fact that they use filters to evaluate which companies are included in them.

#### Segment filters can be constructed using any combination of the following rules:

- company attributes
- user feature access
- feature metrics
- other segments

### Integrations

Connect Bucket with your existing tools:

- Linear
- Datadog
- Segment
- PostHog
- Amplitude
- Mixpanel
- AWS S3
- Slack

## React SDK Implementation

### Installation

\`\`\`bash
npm i @bucketco/react-sdk
\`\`\`

### Key Features

- Feature toggling with fine-grained targeting
- User feedback collection
- Feature usage tracking
- Remote configuration
- Type-safe feature management

### Basic Setup

1. Add the \`BucketProvider\` to wrap your application:

\`\`\`jsx
import { BucketProvider } from "@bucketco/react-sdk";

<BucketProvider
  publishableKey="{YOUR_PUBLISHABLE_KEY}"
  company={{ id: "acme_inc", plan: "pro" }}
  user={{ id: "john_doe" }}
>
  <YourApp />
</BucketProvider>;
\`\`\`

1. Create a feature and generate type-safe definitions:

\`\`\`bash
npm i --save-dev @bucketco/cli
npx bucket new "Feature name"
\`\`\`

\`\`\`typescript
// DO NOT EDIT THIS FILE. IT IS GENERATED BY THE BUCKET CLI AND WILL BE OVERWRITTEN.
// eslint-disable
// prettier-ignore
import "@bucketco/react-sdk";

declare module "@bucketco/react-sdk" {
  export interface Features {
    "feature-key": {
      config: {
        payload: {
          tokens: number;
        };
      };
    };
  }
}
\`\`\`

1. Use features in your components:

\`\`\`jsx
import { useFeature } from "@bucketco/react-sdk";

function StartHuddleButton() {
  const {
    isLoading, // true while features are being loaded
    isEnabled, // boolean indicating if the feature is enabled
    config: {
      // feature configuration
      key, // string identifier for the config variant
      payload, // type-safe configuration object
    },
    track, // function to track feature usage
    requestFeedback, // function to request feedback for this feature
  } = useFeature("huddle");

  if (isLoading) {
    return <Loading />;
  }

  if (!isEnabled) {
    return null;
  }

  return (
    <>
      <button onClick={track}>Start huddle!</button>
      <button
        onClick={(e) =>
          requestFeedback({
            title: payload?.question ?? "How do you like the Huddles feature?",
            position: {
              type: "POPOVER",
              anchor: e.currentTarget as HTMLElement,
            },
          })
        }
      >
        Give feedback!
      </button>
    </>
  );
}
\`\`\`

### Core React Hooks

- \`useFeature()\` - Access feature status, config, and tracking
- \`useTrack()\` - Send custom events to Bucket
- \`useRequestFeedback()\` - Open feedback dialog for a feature
- \`useSendFeedback()\` - Programmatically send feedback
- \`useUpdateUser()\` / \`useUpdateCompany()\` - Update user/company data
- \`useUpdateOtherContext()\` - Update session-only context data
- \`useClient()\` - Access the underlying Bucket client

## Node.js SDK Implementation

### Installation

\`\`\`bash
npm i @bucketco/node-sdk
\`\`\`

### Key Features

- Server-side feature flag evaluation
- User and company context management
- Flexible integration options
- Event tracking

### Basic Setup

\`\`\`javascript
import { ReflagClient } from "@bucketco/node-sdk";

const client = new ReflagClient({
  secretKey: process.env.BUCKET_SECRET_KEY,
});

// Check if a feature is enabled
const isEnabled = await client.isEnabled("feature-key", {
  user: { id: "user_123", role: "admin" },
  company: { id: "company_456", plan: "enterprise" },
});
\`\`\`

### Context Management

\`\`\`javascript
// Set user and company context
await client.setContext({
  user: {
    id: "user_123",
    email: "user@example.com",
    role: "admin",
  },
  company: {
    id: "company_456",
    name: "Acme Inc",
    plan: "enterprise",
  },
});

// Check feature after setting context
const isEnabled = await client.isEnabled("feature-key");
\`\`\`

### Feature Configuration

\`\`\`javascript
// Get feature configuration
const config = await client.getConfig("feature-key", {
  user: { id: "user_123" },
  company: { id: "company_456" },
});

// Use the configuration
console.log(config.payload.maxDuration);
\`\`\`

### Event Tracking

\`\`\`javascript
// Track feature usage
await client.track("feature-key", {
  user: { id: "user_123" },
  company: { id: "company_456" },
  metadata: { action: "completed" },
});

// Track custom events
await client.trackEvent("custom-event", {
  user: { id: "user_123" },
  company: { id: "company_456" },
  metadata: { value: 42 },
});
\`\`\`

## Further Resources

- [Official Documentation](mdc:https:/docs.bucket.co)
- [Docs llms.txt](mdc:https:/docs.bucket.co/llms.txt)
- [GitHub Repository](mdc:https:/github.com/bucketco/bucket-javascript-sdk)
- [Example React App](mdc:https:/github.com/bucketco/bucket-javascript-sdk/tree/main/packages/react-sdk/dev)
`.trim();
