name: "@bucket/react-sdk CI"

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      use-playwright:
        required: true
        type: boolean

permissions:
  statuses: write
  checks: write
  contents: read

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
      - name: Restore Node.js dependencies
        run: yarn install --frozen-lockfile
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
        if: ${{ inputs.use-playwright }}
        working-directory: ${{ inputs.working-directory }}
      - id: build
        name: Build the project
        run: yarn build
      - id: test
        name: Test the project
        run: yarn test:ci
        working-directory: ${{ inputs.working-directory }}
      - name: Report test results
        uses: dorny/test-reporter@v1.6.0
        if: ${{ steps.build.conclusion == 'success' }}
        with:
          name: Build & Test Report
          path: "${{ inputs.working-directory }}/junit.xml"
          reporter: jest-junit
      - id: prettier
        if: ${{ steps.test.conclusion == 'success' }}
        name: Check styling
        run: yarn prettier
        working-directory: ${{ inputs.working-directory }}
      - id: lint
        if: ${{ steps.prettier.conclusion == 'success' }}
        name: Check for linting errors
        run: yarn lint:ci
        working-directory: ${{ inputs.working-directory }}
      - name: Annotate from ESLint report
        if: ${{ steps.prettier.conclusion == 'success' }}
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "${{ inputs.working-directory }}/eslint-report.json"
          fail-on-warning: true
