name: "Package CI"

permissions:
  statuses: write
  checks: write
  contents: read

on: [push]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
      - name: Restore Node.js dependencies
        run: yarn install --immutable
      - name: Restore package.json
        # This step is necessary because the previous step may have updated package.json
        run: git checkout -- package.json packages/*/package.json
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
        working-directory: ./packages/tracking-sdk
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
        working-directory: ./packages/browser-sdk
      - id: build
        name: Build the project
        run: yarn build
      - id: test
        name: Test the project
        run: yarn test:ci
      - name: Report test results
        uses: dorny/test-reporter@v1.6.0
        with:
          name: Build & Test Report
          path: ./packages/*/junit.xml
          reporter: jest-junit
      - id: prettier
        name: Check styling
        run: yarn prettier
      - id: lint
        name: Check for linting errors
        run: yarn lint:ci
      - name: Annotate from ESLint report
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: ./packages/*/eslint-report.json
          fail-on-warning: true
