name: Publish updated packages

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
          registry-url: "https://registry.npmjs.org"
          scope: "@reflag"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build packages
        run: yarn build
      - name: npm login
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish
        run: yarn lerna publish from-package --no-private --yes
      - name: Build docs
        run: yarn docs
      - name: Checkout docs with SSH
        uses: actions/checkout@v3
        with:
          repository: bucketco/docs
          ssh-key: ${{ secrets.DOCS_DEPLOY_KEY }}
          path: bucket-docs
      - name: Copy generated docs to docs repo
        run: |
          rm -rf reflag-docs/sdk
          cp -R dist/docs reflag-docs/sdk
      - name: Commit and push changes
        run: |
          cd reflag-docs
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@reflag.com"
          git add sdk
          git commit -m "Update documentation" && git push || echo "No docs changes to commit"
