name: Typescript CI

on: [push]

permissions:
  statuses: write
  checks: write
  contents: read

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.6.x
          cache: "yarn"
      - run: yarn install
      - run: yarn build
      - run: yarn test:ci
      - name: Test Reporter
        uses: dorny/test-reporter@v1.5.0
        if: always() # run this step even if previous step failed
        with:
          name: Build & Test Report # Name of the check run which will be created
          path: ./junit.xml # Path to test results
          reporter: java-junit # Format of test results
